<?php require_once __DIR__ . '/../../controllers/marketing_importsController.php'; require_once __DIR__ . '/marketing_helpers.php'; ?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Marketing - Importar Meta Ads</title><link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"><link rel="stylesheet" href="../../assets/framework/framework.css"><script src="../../assets/framework/framework.js" defer></script><script src="https://cdn.jsdelivr.net/npm/papaparse@5.4.1/papaparse.min.js"></script><link rel="stylesheet" href="marketing_styles.css"></head><body><div class="layout"><?php require __DIR__ . '/../../partials/marketing_nav.php'; ?><main class="main"><header class="navbar"><div class="navbar-left"><button class="btn-icon" onclick="toggleSidebar()"><span class="material-icons">menu</span></button><div class="navbar-title">Importar CSV Meta Ads</div></div><?= renderBotonPerfil($perfil['avatar_path'] ?? ($_SESSION['avatar_path'] ?? null)) ?></header><section class="content page-stack"><?php if (($flash['message'] ?? '') !== ''): ?><div class="flash <?= mh($flash['type']) ?>"><?= mh($flash['message']) ?></div><?php endif; ?>
<form class="marketing-card" method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="upload_csv"><h2>Subir CSV</h2><input type="file" name="meta_csv" id="metaCsv" accept=".csv,text/csv" required><div id="csvPreview" class="empty">Selecciona un CSV para previsualizar columnas y primeras filas.</div><button class="btn btn-aceptar" type="submit">Confirmar importacion</button></form>
<?php if ($importResult): ?><div class="marketing-card"><h2>Resumen final</h2><div class="kpi-grid"><div class="kpi-card"><span>Filas totales</span><strong><?= (int)$importResult['total'] ?></strong></div><div class="kpi-card"><span>Importadas</span><strong><?= (int)$importResult['imported'] ?></strong></div><div class="kpi-card"><span>Omitidas</span><strong><?= (int)$importResult['skipped'] ?></strong></div><div class="kpi-card"><span>Sin resolver</span><strong><?= (int)$importResult['unresolved'] ?></strong></div><div class="kpi-card"><span>Inversion</span><strong><?= money($importResult['summary']['spent'] ?? 0) ?></strong></div><div class="kpi-card"><span>Impresiones</span><strong><?= number_format((float)($importResult['summary']['impressions'] ?? 0),0,',','.') ?></strong></div></div></div><?php endif; ?>
<div class="marketing-card"><h2>Asignaciones manuales pendientes</h2><div class="table-wrap"><table class="marketing-table"><thead><tr><th>Campaña externa</th><th>Fila</th><th>Asignar a campaña interna</th></tr></thead><tbody><?php foreach($filasSinResolver as $row): ?><tr><td><?= mh($row['external_campaign_name'] ?? '') ?></td><td><?= (int)$row['csv_row_number'] ?></td><td><form method="post" class="actions-row"><input type="hidden" name="action" value="save_mapping"><input type="hidden" name="external_campaign_name" value="<?= mh($row['external_campaign_name'] ?? '') ?>"><select name="internal_campaign_id" required><option value="">Campaña interna</option><?php foreach($campanias as $c): ?><option value="<?= (int)$c['id'] ?>"><?= mh(($c['user_label'] ?? '') . ' - ' . ($c['campaign_name'] ?? '')) ?></option><?php endforeach; ?></select><button class="btn btn-aceptar" type="submit">Guardar mapping</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php if(empty($filasSinResolver)): ?><div class="empty">No hay filas sin resolver.</div><?php endif; ?></div>
<div class="marketing-card"><h2>Ultimas importaciones</h2><div class="table-wrap"><table class="marketing-table"><thead><tr><th>Archivo</th><th>Estado</th><th>Total</th><th>Importadas</th><th>Sin resolver</th><th>Fecha</th></tr></thead><tbody><?php foreach($importaciones as $i): ?><tr><td><?= mh($i['original_filename'] ?? '') ?></td><td><?= statusLabel($i['status'] ?? '') ?></td><td><?= (int)($i['total_rows'] ?? 0) ?></td><td><?= (int)($i['imported_rows'] ?? 0) ?></td><td><?= (int)($i['unresolved_rows'] ?? 0) ?></td><td><?= mh($i['created_at'] ?? '') ?></td></tr><?php endforeach; ?></tbody></table></div></div>
</section></main></div><script>
const requiredColumns=['Inicio del informe','Fin del informe','Nombre de la campaña','Importe gastado (ARS)','Impresiones','Alcance'];
document.getElementById('metaCsv')?.addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;Papa.parse(file,{header:true,preview:6,complete:(res)=>{const cols=res.meta.fields||[];const missing=requiredColumns.filter(c=>!cols.includes(c));const rows=res.data||[];document.getElementById('csvPreview').innerHTML='<strong>Columnas detectadas:</strong> '+cols.join(', ')+'<br><strong>Validacion:</strong> '+(missing.length?'Faltan '+missing.join(', '):'Columnas obligatorias OK')+'<br><strong>Filas de muestra:</strong> '+rows.length;}});});
</script><?php $perfilObligatorio=false; require_once __DIR__ . '/../../partials/modal_perfil/modal_perfil.php'; ?></body></html>
